# This name is shit
saturation:
  initial_agents : 1
  nodes : 250
  structure : sparse_erdos
  simulation_iterations : 5
  transmittion_prob : 1
  max_iterations : 500

#Configuration for main_reachability
reachability:
  num_simulation_runs : 20
  random_geometric:
    structure_name : "random_geometric"
    nodes : 500 
    graph_edge_radii : [0.025, 0.05, 0.1] #[0.025, 0.05, 0.08, 0.12, 0.18, 0.25]



  barabasi_albert:
    structure_name : "barabasi_albert"  
    nodes : 500 
    node_degree : [2,5,8,10, 20]
# Configuration for graph visualizations
VIZ:
# Where to output .png files representing graph structures.
  output_dir : data
