# This name is shit
saturation:
  initial_agents : 1
  nodes : 250
  structure : sparse_erdos
  simulation_iterations : 5
  transmittion_prob : 1
  max_iterations : 500

#Configuration for main_reachability
reachability:
  num_simulation_runs : 20
  mean_degrees : [2,5,10,15,20]

  nodes : 500
  structure_names : ["random_geometric", "barabasi_albert"]
  
# Configuration for graph visualizations
VIZ:
# Where to output .png files representing graph structures.
  output_dir : data
